name: Tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn global add pnpm
      - run: pnpm install
        working-directory: scripts
      - run: node prepare.js
        working-directory: scripts
