name: Post-deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn global add pnpm
      - name: update file and push to remote
        run: |
          pnpm install
          node prepare.js
          
          git config --global user.name "ktw-prepare"
          git config --global user.email "kenan@sly.mn"
          
          git status
          git add -A
          git checkout -b pages
          git commit -m "post-deploy-$(date "+%Y-%m-%d-%H:%M:%S")"
          git push -u origin pages
        working-directory: scripts
